apiVersion: v1
kind: List
items:
  ################### pod #######################
  ###### router-1 ######
  - apiVersion: v1
    kind: Pod
    metadata:
      name: router-1
      labels:
        name: tunnel
    spec:
      containers:
        - name: tunnel
          image: frrouting/frr:v8.2.2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /etc/frr/daemons
              subPath: daemons
            - name: config
              mountPath: /etc/frr/frr.conf
              subPath: frr.conf
      volumes:
        - name: config
          configMap:
            name: router-1
  ###### router-2 ######
  - apiVersion: v1
    kind: Pod
    metadata:
      name: router-2
      labels:
        name: tunnel
    spec:
      containers:
        - name: tunnel
          image: frrouting/frr:v8.2.2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /etc/frr/daemons
              subPath: daemons
            - name: config
              mountPath: /etc/frr/frr.conf
              subPath: frr.conf
      volumes:
        - name: config
          configMap:
            name: router-2
  ###### router-3 ######
  - apiVersion: v1
    kind: Pod
    metadata:
      name: router-3
      labels:
        name: tunnel
    spec:
      containers:
        - name: tunnel
          image: frrouting/frr:v8.2.2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /etc/frr/daemons
              subPath: daemons
            - name: config
              mountPath: /etc/frr/frr.conf
              subPath: frr.conf
      volumes:
        - name: config
          configMap:
            name: router-3
  ###### router-4 ######
  - apiVersion: v1
    kind: Pod
    metadata:
      name: router-4
      labels:
        name: tunnel
    spec:
      containers:
        - name: tunnel
          image: frrouting/frr:v8.2.2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /etc/frr/daemons
              subPath: daemons
            - name: config
              mountPath: /etc/frr/frr.conf
              subPath: frr.conf
      volumes:
        - name: config
          configMap:
            name: router-4
  ###### router-5 ######
  - apiVersion: v1
    kind: Pod
    metadata:
      name: router-5
      labels:
        name: tunnel
    spec:
      containers:
        - name: tunnel
          image: frrouting/frr:v8.2.2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /etc/frr/daemons
              subPath: daemons
            - name: config
              mountPath: /etc/frr/frr.conf
              subPath: frr.conf
      volumes:
        - name: config
          configMap:
            name: router-5
  ###### router-6 ######
  - apiVersion: v1
    kind: Pod
    metadata:
      name: router-6
      labels:
        name: tunnel
    spec:
      containers:
        - name: tunnel
          image: frrouting/frr:v8.2.2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /etc/frr/daemons
              subPath: daemons
            - name: config
              mountPath: /etc/frr/frr.conf
              subPath: frr.conf
      volumes:
        - name: config
          configMap:
            name: router-6
  ###### router-7 ######
  - apiVersion: v1
    kind: Pod
    metadata:
      name: router-7
      labels:
        name: tunnel
    spec:
      containers:
        - name: tunnel
          image: frrouting/frr:v8.2.2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /etc/frr/daemons
              subPath: daemons
            - name: config
              mountPath: /etc/frr/frr.conf
              subPath: frr.conf
      volumes:
        - name: config
          configMap:
            name: router-7
  ###### router-8 ######
  - apiVersion: v1
    kind: Pod
    metadata:
      name: router-8
      labels:
        name: tunnel
    spec:
      containers:
        - name: tunnel
          image: frrouting/frr:v8.2.2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /etc/frr/daemons
              subPath: daemons
            - name: config
              mountPath: /etc/frr/frr.conf
              subPath: frr.conf
      volumes:
        - name: config
          configMap:
            name: router-8
  ###### router-9 ######
  - apiVersion: v1
    kind: Pod
    metadata:
      name: router-9
      labels:
        name: tunnel
    spec:
      containers:
        - name: tunnel
          image: frrouting/frr:v8.2.2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /etc/frr/daemons
              subPath: daemons
            - name: config
              mountPath: /etc/frr/frr.conf
              subPath: frr.conf
      volumes:
        - name: config
          configMap:
            name: router-9
  ###### router-10 ######
  - apiVersion: v1
    kind: Pod
    metadata:
      name: router-10
      labels:
        name: tunnel
    spec:
      containers:
        - name: tunnel
          image: frrouting/frr:v8.2.2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /etc/frr/daemons
              subPath: daemons
            - name: config
              mountPath: /etc/frr/frr.conf
              subPath: frr.conf
      volumes:
        - name: config
          configMap:
            name: router-10

  ################### topo #######################
  ###### router-1 ######
  - apiVersion: networkop.co.uk/v1beta1
    kind: Topology
    metadata:
      name: router-1
    spec:
      links:
        - uid: 2218012
          peer_pod: router-2
          local_intf: eth1
          peer_intf: eth1
          local_ip: 10.0.1.1/24
          peer_ip: 10.0.1.2/24
        - uid: 2218013
          peer_pod: router-3
          local_intf: eth2
          peer_intf: eth1
          local_ip: 10.0.2.1/24
          peer_ip: 10.0.2.2/24
  ###### router-2 ######
  - apiVersion: networkop.co.uk/v1beta1
    kind: Topology
    metadata:
      name: router-2
    spec:
      links:
        - uid: 2218012
          peer_pod: router-1
          local_intf: eth1
          peer_intf: eth1
          local_ip: 10.0.1.2/24
          peer_ip: 10.0.1.1/24
        - uid: 2218023
          peer_pod: router-3
          local_intf: eth2
          peer_intf: eth2
          local_ip: 10.0.3.1/24
          peer_ip: 10.0.3.2/24
  ###### router-3 ######
  - apiVersion: networkop.co.uk/v1beta1
    kind: Topology
    metadata:
      name: router-3
    spec:
      links:
        - uid: 2218013
          peer_pod: router-1
          local_intf: eth1
          peer_intf: eth2
          local_ip: 10.0.2.2/24
          peer_ip: 10.0.2.1/24
        - uid: 2218023
          peer_pod: router-2
          local_intf: eth2
          peer_intf: eth2
          local_ip: 10.0.3.2/24
          peer_ip: 10.0.3.1/24
        - uid: 2218034
          peer_pod: router-4
          local_intf: eth3
          peer_intf: eth1
          local_ip: 10.0.4.1/24
          peer_ip: 10.0.4.2/24
        - uid: 2218035
          peer_pod: router-5
          local_intf: eth4
          peer_intf: eth1
          local_ip: 10.0.5.1/24
          peer_ip: 10.0.5.2/24
        - uid: 2218036
          peer_pod: router-6
          local_intf: eth5
          peer_intf: eth1
          local_ip: 10.0.6.1/24
          peer_ip: 10.0.6.2/24
  ###### router-4 ######
  - apiVersion: networkop.co.uk/v1beta1
    kind: Topology
    metadata:
      name: router-4
    spec:
      links:
        - uid: 2218034
          peer_pod: router-3
          local_intf: eth1
          peer_intf: eth3
          local_ip: 10.0.4.2/24
          peer_ip: 10.0.4.1/24
        - uid: 2218045
          peer_pod: router-5
          local_intf: eth2
          peer_intf: eth2
          local_ip: 10.0.7.1/24
          peer_ip: 10.0.7.2/24
        - uid: 2218047
          peer_pod: router-7
          local_intf: eth3
          peer_intf: eth1
          local_ip: 10.0.8.1/24
          peer_ip: 10.0.8.2/24
  ###### router-5 ######
  - apiVersion: networkop.co.uk/v1beta1
    kind: Topology
    metadata:
      name: router-5
    spec:
      links:
        - uid: 2218035
          peer_pod: router-3
          local_intf: eth1
          peer_intf: eth4
          local_ip: 10.0.5.2/24
          peer_ip: 10.0.5.1/24
        - uid: 2218045
          peer_pod: router-4
          local_intf: eth2
          peer_intf: eth2
          local_ip: 10.0.7.2/24
          peer_ip: 10.0.7.1/24
        - uid: 2218058
          peer_pod: router-8
          local_intf: eth3
          peer_intf: eth2
          local_ip: 10.0.10.1/24
          peer_ip: 10.0.10.2/24
  ###### router-6 ######
  - apiVersion: networkop.co.uk/v1beta1
    kind: Topology
    metadata:
      name: router-6
    spec:
      links:
        - uid: 2218036
          peer_pod: router-3
          local_intf: eth1
          peer_intf: eth5
          local_ip: 10.0.6.2/24
          peer_ip: 10.0.6.1/24
        - uid: 2218068
          peer_pod: router-8
          local_intf: eth2
          peer_intf: eth1
          local_ip: 10.0.9.1/24
          peer_ip: 10.0.9.2/24
  ###### router-7 ######
  - apiVersion: networkop.co.uk/v1beta1
    kind: Topology
    metadata:
      name: router-7
    spec:
      links:
        - uid: 2218047
          peer_pod: router-4
          local_intf: eth1
          peer_intf: eth3
          local_ip: 10.0.8.2/24
          peer_ip: 10.0.8.1/24
        - uid: 2218078
          peer_pod: router-8
          local_intf: eth2
          peer_intf: eth3
          local_ip: 10.0.11.1/24
          peer_ip: 10.0.11.2/24
  ###### router-8 ######
  - apiVersion: networkop.co.uk/v1beta1
    kind: Topology
    metadata:
      name: router-8
    spec:
      links:
        - uid: 2218058
          peer_pod: router-5
          local_intf: eth2
          peer_intf: eth3
          local_ip: 10.0.10.2/24
          peer_ip: 10.0.10.1/24
        - uid: 2218068
          peer_pod: router-6
          local_intf: eth1
          peer_intf: eth2
          local_ip: 10.0.9.2/24
          peer_ip: 10.0.9.1/24
        - uid: 2218078
          peer_pod: router-7
          local_intf: eth3
          peer_intf: eth2
          local_ip: 10.0.11.2/24
          peer_ip: 10.0.11.1/24
        - uid: 2218089
          peer_pod: router-9
          local_intf: eth5
          peer_intf: eth1
          local_ip: 10.0.13.1/24
          peer_ip: 10.0.13.2/24
        - uid: 2218080
          peer_pod: router-10
          local_intf: eth4
          peer_intf: eth1
          local_ip: 10.0.12.1/24
          peer_ip: 10.0.12.2/24
  ###### router-9 ######
  - apiVersion: networkop.co.uk/v1beta1
    kind: Topology
    metadata:
      name: router-9
    spec:
      links:
        - uid: 2218089
          peer_pod: router-8
          local_intf: eth1
          peer_intf: eth5
          local_ip: 10.0.13.2/24
          peer_ip: 10.0.13.1/24
        - uid: 2218090
          peer_pod: router-10
          local_intf: eth2
          peer_intf: eth2
          local_ip: 10.0.14.1/24
          peer_ip: 10.0.14.2/24
  ###### router-10 ######
  - apiVersion: networkop.co.uk/v1beta1
    kind: Topology
    metadata:
      name: router-10
    spec:
      links:
        - uid: 2218080
          peer_pod: router-8
          local_intf: eth1
          peer_intf: eth4
          local_ip: 10.0.12.2/24
          peer_ip: 10.0.12.1/24
        - uid: 2218090
          peer_pod: router-9
          local_intf: eth2
          peer_intf: eth2
          local_ip: 10.0.14.2/24
          peer_ip: 10.0.14.1/24
